
# List of gallery names to load from /images/galleries/
galleries:
  - nature
  - street
  - travel

# Featured images displayed on the home page
featured:
  - url: "https://images.unsplash.com/photo-1472396961693-142e6e269027"
    alt: "Two brown deer beside trees and mountain"
    exif:
      camera: "Canon EOS R5"
      shutterSpeed: "1/1000"
      aperture: "2.8"
      iso: "100"
      focalLength: "70"
  - url: "https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07"
    alt: "Orange flowers in city"
    exif:
      camera: "Sony A7R V"
      shutterSpeed: "1/2000"
      aperture: "1.8"
      iso: "100"
      focalLength: "85"
  - url: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9"
    alt: "Abstract pine trees"
    exif:
      camera: "Fujifilm X-T4"
      shutterSpeed: "1/250"
      aperture: "2.0"
      iso: "200"
      focalLength: "56"
  - url: "https://images.unsplash.com/photo-1433086966358-54859d0ed716"
    alt: "Majestic waterfall"
    exif:
      camera: "Canon EOS R5"
      shutterSpeed: "1/1000"
      aperture: "8.0"
      iso: "100"
      focalLength: "16"
  - url: "https://images.unsplash.com/photo-1482938289607-e9573fc25ebb"
    alt: "River between mountains"
    exif:
      camera: "Canon EOS R6"
      shutterSpeed: "1/2000"
      aperture: "8.0"
      iso: "100"
      focalLength: "24"
