
# List of gallery names to load
galleries:
  - id: "1"
    title: "Nature"
    images:
      - url: "/images/galleries/nature/_MG_8056.jpg"
        alt: "Forest landscape"
      - url: "/images/galleries/nature/_MG_8078.jpg"
        alt: "Mountain sunset"
      - url: "/images/galleries/nature/_MG_8085.jpg"
        alt: "Misty forest"
      - url: "/images/galleries/nature/untitled-1589.jpg"
        alt: "Peaceful lake"
  
  - id: "2"
    title: "Street"
    images:
      - url: "/images/galleries/street/L1001660.jpg"
        alt: "Urban street scene"
  
  - id: "3"
    title: "Travel"
    images:
      - url: "/images/galleries/travel/IMG_5897.jpg"
        alt: "Exotic destination"

# Featured images displayed on the home page
featured:
  - url: "/images/galleries/nature/_MG_8056.jpg"
    alt: "Forest landscape"
  - url: "/images/galleries/nature/_MG_8078.jpg"
    alt: "Mountain sunset"
  - url: "/images/galleries/street/L1001660.jpg"
    alt: "Urban street scene"
  - url: "/images/galleries/travel/IMG_5897.jpg"
    alt: "Exotic destination"
  - url: "/images/galleries/nature/untitled-1589.jpg"
    alt: "Peaceful lake"
