
# List of gallery names to load from /images/galleries/
galleries:
  - nature
  - street
  - travel

# Featured images displayed on the home page
featured:
  - url: "https://images.unsplash.com/photo-1472396961693-142e6e269027"
    alt: "Two brown deer beside trees and mountain"
  - url: "https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07"
    alt: "Orange flowers in city"
  - url: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9"
    alt: "Abstract pine trees"
  - url: "https://images.unsplash.com/photo-1433086966358-54859d0ed716"
    alt: "Majestic waterfall"
  - url: "https://images.unsplash.com/photo-1482938289607-e9573fc25ebb"
    alt: "River between mountains"
