
# List of gallery names to load
galleries:
  - id: "1"
    title: "Nature"
    images:
      - url: "/images/galleries/nature/_MG_8056.jpg"
        alt: "Forest landscape"
        exif:
          camera: "Canon EOS 5D Mark III"
          shutterSpeed: "1/125"
          aperture: "11"
          iso: "100"
          focalLength: "24"
      - url: "/images/galleries/nature/_MG_8078.jpg"
        alt: "Mountain sunset"
        exif:
          camera: "Canon EOS 5D Mark III"
          shutterSpeed: "1/60"
          aperture: "8"
          iso: "200"
          focalLength: "70"
      - url: "/images/galleries/nature/_MG_8085.jpg"
        alt: "Misty forest"
        exif:
          camera: "Canon EOS 5D Mark III"
          shutterSpeed: "1/30"
          aperture: "5.6"
          iso: "400"
          focalLength: "35"
      - url: "/images/galleries/nature/untitled-1589.jpg"
        alt: "Peaceful lake"
        exif:
          camera: "Canon EOS 5D Mark III"
          shutterSpeed: "1/250"
          aperture: "16"
          iso: "100"
          focalLength: "24"
  
  - id: "2"
    title: "Street"
    images:
      - url: "/images/galleries/street/L1001660.jpg"
        alt: "Urban street scene"
        exif:
          camera: "Leica Q2"
          shutterSpeed: "1/500"
          aperture: "5.6"
          iso: "400"
          focalLength: "28"
  
  - id: "3"
    title: "Travel"
    images:
      - url: "/images/galleries/travel/IMG_5897.jpg"
        alt: "Exotic destination"
        exif:
          camera: "Sony A7R IV"
          shutterSpeed: "1/800"
          aperture: "8"
          iso: "100"
          focalLength: "35"

# Featured images displayed on the home page
featured:
  - url: "https://images.unsplash.com/photo-1472396961693-142e6e269027"
    alt: "Two brown deer beside trees and mountain"
    exif:
      camera: "Canon EOS R5"
      shutterSpeed: "1/1000"
      aperture: "2.8"
      iso: "100"
      focalLength: "70"
  - url: "https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07"
    alt: "Orange flowers in city"
    exif:
      camera: "Sony A7R V"
      shutterSpeed: "1/2000"
      aperture: "1.8"
      iso: "100"
      focalLength: "85"
  - url: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9"
    alt: "Abstract pine trees"
    exif:
      camera: "Fujifilm X-T4"
      shutterSpeed: "1/250"
      aperture: "2.0"
      iso: "200"
      focalLength: "56"
  - url: "https://images.unsplash.com/photo-1433086966358-54859d0ed716"
    alt: "Majestic waterfall"
    exif:
      camera: "Canon EOS R5"
      shutterSpeed: "1/1000"
      aperture: "8.0"
      iso: "100"
      focalLength: "16"
  - url: "https://images.unsplash.com/photo-1482938289607-e9573fc25ebb"
    alt: "River between mountains"
    exif:
      camera: "Canon EOS R6"
      shutterSpeed: "1/2000"
      aperture: "8.0"
      iso: "100"
      focalLength: "24"
